export interface SeedProduct {
  id: string;
  name: string;
  brand: string;
  product_line: string;
  category: string;
  wacker_sku?: string;
  cas_numbers?: string;
  chemical_components?: string;
  chemical_synonyms?: string;
  inci_name?: string;
  physical_form?: string;
  density?: string;
  flash_point?: string;
  grade?: string;
  purity?: string;
  shelf_life?: string;
  temperature_range?: string;
  cure_system?: string;
  main_application: string;
  un_number?: string;
  product_url?: string;
  producer: string;
  description: string;
  // Compliance
  wiaw_status?: "GREEN" | "ATTENTION" | "RED";
  sales_advisory?: string;
  extraction_status?: "complete" | "partial" | "in_progress";
  completeness: number;
  certifications?: string[];
  ghs_statements?: string;
  global_inventories?: string[];
  blocked_countries?: string[];
  blocked_industries?: string[];
  usage_restrictions?: string;
  packaging_options?: string;
  material_numbers?: string;
  // Documents
  tds_available: boolean;
  sds_available: boolean;
  rpi_available: boolean;
  coa_available: boolean;
  // Legacy arrays (keep for backward compat, can be empty)
  key_properties: string[];
  applications: string[];
  benefits: string[];
}

export const BRANDS = [
  "BELSIL",
  "ELASTOSIL",
  "GENIOSIL",
  "VINNAPAS",
  "POWERSIL",
  "FERMOPURE",
] as const;

export const SEED_PRODUCTS: SeedProduct[] = [
  // ============================================================
  // BELSIL products (12)
  // ============================================================
  {
    id: "belsil-dm-065",
    name: "BELSIL DM 0.65",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids",
    completeness: 35,
    physical_form: "Liquid (colorless, clear, low viscosity)",
    chemical_synonyms: "Disiloxane (INCI)",
    main_application: "Volatile silicone for cosmetics",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-dm-065/p/000004657",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Colorless, clear fluid of low viscosity and high volatility. Evaporates from the skin without producing a cooling or stinging effect.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-dm-10",
    name: "BELSIL DM 10",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids",
    completeness: 35,
    physical_form: "Liquid (dimethicone)",
    chemical_synonyms: "Dimethicone 10 cSt (INCI)",
    main_application: "Low viscosity dimethicone",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-dm-10/p/000004660",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Low viscosity polydimethylsiloxane fluid used in personal care applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-dm-100",
    name: "BELSIL DM 100",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids",
    completeness: 35,
    physical_form: "Liquid",
    main_application: "Medium viscosity dimethicone",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Linear, non-reactive polydimethylsiloxane with low surface tension and high spreading coefficient.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-adm-1370",
    name: "BELSIL ADM 1370",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids, Functional",
    completeness: 35,
    physical_form: "Liquid (aminofunctional)",
    chemical_synonyms: "Amodimethicone (INCI)",
    main_application: "Hair care conditioning",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-adm-1370/p/000004623",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Aminofunctional polydimethylsiloxane with low odor profile. Ideal for sensitive personal care applications, particularly hair care formulations.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-adm-1650",
    name: "BELSIL ADM 1650",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids, Functional",
    completeness: 35,
    physical_form: "Liquid (aminofunctional)",
    chemical_synonyms: "Amodimethicone (INCI)",
    main_application: "Hair care conditioning",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-adm-1650/p/000003456",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Aminofunctional polydimethylsiloxane for hair care conditioning with enhanced deposition properties.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-eg-6000",
    name: "BELSIL EG 6000",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Elastomer Gels",
    completeness: 35,
    physical_form: "Gel (silicone elastomer)",
    chemical_synonyms: "Dimethicone/Vinyl Dimethicone Crosspolymer (INCI)",
    main_application: "Silicone elastomer gel",
    product_url:
      "https://www.wacker.com/h/en-us/silicones/silicone-fluids-emulsions/belsil-eg-6000/p/000004713",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Silicone copolymer network blended with volatile dimethicone. Transparent, colorless gel with excellent shear-thinning behavior.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-tms-803",
    name: "BELSIL TMS 803",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Resins",
    completeness: 35,
    physical_form: "Resin",
    main_application: "Water-resistant products",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Three-dimensional siloxane polymer network with unique resin properties for cosmetic and personal care formulations.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-p-1101",
    name: "BELSIL P 1101",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Copolymers",
    completeness: 35,
    physical_form: "Liquid",
    chemical_synonyms: "PEG/PPG-20/23 Dimethicone (INCI)",
    main_application: "Water-soluble silicone",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-p-1101/p/000004725",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Water-soluble silicone copolymer for personal care applications with emulsifying properties.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-gb-1020",
    name: "BELSIL GB 1020",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Gum Blends",
    completeness: 35,
    physical_form: "Gel",
    main_application: "Anti-frizz products",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Silicone gum blend for personal care formulations providing conditioning and anti-frizz benefits.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-dmc-6031",
    name: "BELSIL DMC 6031",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Copolymers",
    completeness: 35,
    physical_form: "Liquid",
    chemical_synonyms: "PEG/PPG-18/18 Dimethicone (INCI)",
    main_application: "Water-soluble copolymer",
    product_url:
      "https://www.wacker.com/h/en-us/c/belsil-dmc-6031/p/000004706",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Water-soluble silicone copolymer with emulsifying properties for personal care formulations.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-dm-6101-e",
    name: "BELSIL DM 6101 E",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Emulsions",
    completeness: 35,
    physical_form: "Emulsion",
    main_application: "Silicone emulsion",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Pre-emulsified dimethicone for easy incorporation into aqueous personal care formulations.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "belsil-cdm-3526-vp",
    name: "BELSIL CDM 3526 VP",
    brand: "BELSIL",
    product_line: "BELSIL\u00AE",
    category: "Silicone Fluids, Functional",
    completeness: 35,
    physical_form: "Liquid",
    main_application: "Conditioning silicone",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Conditioning silicone fluid for hair and skin care applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },

  // ============================================================
  // ELASTOSIL products (28)
  // ============================================================
  {
    id: "elastosil-4100",
    name: "ELASTOSIL 4100",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 87,
    physical_form: "Paste (non-sag cartridge sealant)",
    cas_numbers: "17689-77-9, 4253-34-3, 64359-81-5, 335-00-8",
    density: "1.02 g/cm\u00B3 (uncured @ 23\u00B0C)",
    cure_system: "Acetoxy",
    main_application: "Sanitary applications",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-4100/p/000005005",
    extraction_status: "partial",
    wiaw_status: "RED",
    sales_advisory:
      "\u26A0\uFE0F CAUTION - Industry restriction applies. This product is not suitable for food & beverage, food packaging, electronics, and marine hardware.",
    blocked_industries: [
      "Food & Beverage",
      "Food Packaging",
      "Electronics",
      "Marine Hardware",
    ],
    grade: "Sanitary Grade (RTV-1 Sealant)",
    purity: "Mixture (100% silicone, one-component)",
    shelf_life: "12 months",
    temperature_range: "-40 to +180\u00B0C (short-term up to +200\u00B0C)",
    producer: "Wacker Chemie AG",
    description:
      "One-component, acetoxy-curing silicone sealant for sanitary applications with built-in fungicide protection.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-4300",
    name: "ELASTOSIL 4300",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste (non-sag cartridge sealant)",
    cas_numbers: "17689-77-9, 4253-34-3, 64359-81-5, 335-00-8",
    density: "1.03 g/cm\u00B3 (uncured @ 23\u00B0C)",
    flash_point: "65\u00B0C",
    cure_system: "Acetoxy",
    main_application: "General purpose sealing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-4300/p/000005007",
    extraction_status: "partial",
    wiaw_status: "RED",
    blocked_industries: [
      "Food & Beverage",
      "Food Packaging",
      "Marine Hardware",
    ],
    grade: "General Purpose (RTV-1 Sealant)",
    shelf_life: "12 months",
    temperature_range: "-40 to +180\u00B0C (short-term up to +200\u00B0C)",
    producer: "Wacker Chemie AG",
    description:
      "One-component, acetoxy-curing general purpose silicone sealant for construction and industrial applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-4500",
    name: "ELASTOSIL 4500",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "High temperature applications",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-4500/p/000005009",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +250\u00B0C (short-term up to +275\u00B0C)",
    producer: "Wacker Chemie AG",
    description:
      "One-component, acid-curing silicone sealant for high temperature applications up to 250\u00B0C.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-4710",
    name: "ELASTOSIL 4710",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "Aquarium/glass bonding",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +180\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant with excellent adhesion to glass for aquarium and bonding applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-4003",
    name: "ELASTOSIL 4003",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste (non-sag cartridge sealant, low-modulus)",
    density: "1.02 g/cm\u00B3 (uncured @ 23\u00B0C)",
    cure_system: "Acetoxy",
    main_application: "DIY applications",
    product_url:
      "https://www.wacker.com/h/en-us/c/elastosil-4003/p/000100419",
    extraction_status: "partial",
    wiaw_status: "RED",
    grade: "Food Contact Grade (RTV-1 Sealant)",
    purity: "Mixture (100% silicone, one-component)",
    temperature_range: "-40 to +180\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant for DIY applications with low-modulus flexibility.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-5000",
    name: "ELASTOSIL 5000",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "Construction/glazing",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +180\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant for construction and glazing applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-5010",
    name: "ELASTOSIL 5010",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Acetoxy",
    main_application: "Construction/glazing, low-modulus",
    product_url:
      "https://www.wacker.com/h/en-us/c/elastosil-5010/p/000102531",
    extraction_status: "in_progress",
    temperature_range: "-40 bis +160\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant for low-modulus construction and glazing applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-5002",
    name: "ELASTOSIL 5002",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Acetoxy",
    main_application: "General construction",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant for general construction applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-5100",
    name: "ELASTOSIL 5100",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "Construction/glazing, high-modulus",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +150\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing high-modulus silicone sealant for construction and glazing.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-5605",
    name: "ELASTOSIL 5605",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Acetoxy",
    main_application: "Structural glazing",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing silicone sealant for structural glazing applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-6000",
    name: "ELASTOSIL 6000",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "Sanitary sealing, mold-resistant",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +180\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component acetoxy-curing sanitary silicone sealant with excellent mold resistance.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-6100",
    name: "ELASTOSIL 6100",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 86,
    physical_form: "Paste",
    cure_system: "Acetoxy",
    main_application: "Sanitary sealing, premium",
    extraction_status: "partial",
    wiaw_status: "RED",
    temperature_range: "-40 to +180\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "Premium one-component acetoxy-curing sanitary silicone sealant with enhanced mold protection.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-7000-n",
    name: "ELASTOSIL 7000 N",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Oxime",
    main_application: "Construction/glazing, neutral-curing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-7000-n/p/000005018",
    extraction_status: "in_progress",
    temperature_range: "-40 to +150\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component neutral-curing (oxime) silicone sealant for construction and glazing applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-7750-n",
    name: "ELASTOSIL 7750 N",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Oxime",
    main_application: "High-movement joint sealing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-7750-n/p/000005019",
    extraction_status: "in_progress",
    temperature_range: "-40 to +150\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component neutral-curing (oxime) silicone sealant for high-movement joint sealing.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-8000-n",
    name: "ELASTOSIL 8000 N",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Oxime",
    main_application: "Perimeter sealing/glazing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-8000-n/p/000005017",
    extraction_status: "in_progress",
    temperature_range: "-40 to +150\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component neutral-curing (oxime) silicone sealant for perimeter sealing and glazing.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-9000-n",
    name: "ELASTOSIL 9000 N",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Sealants",
    completeness: 30,
    cure_system: "Alkoxy",
    main_application: "DIY, alkaline substrates",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-sealants/finished-sealants/elastosil-9000-n/p/000005064",
    extraction_status: "in_progress",
    temperature_range: "-40 to +150\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "One-component alkoxy-curing silicone sealant for DIY use on alkaline substrates.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-47007",
    name: "ELASTOSIL 47007",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Fluids",
    completeness: 30,
    main_application: "Silicone fluid",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Polydimethylsiloxane silicone fluid for industrial release and lubrication applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-a316",
    name: "ELASTOSIL A316",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Silicone Coatings",
    completeness: 25,
    physical_form: "Solvent-based dispersion",
    cure_system: "Amine",
    main_application: "Protective coating against moisture",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-rubber/moisture-curing-silicone-rubber-rtv-1/elastosil-a316/p/000005081",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Solvent-based silicone dispersion for protective coatings against moisture.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-n-2010",
    name: "ELASTOSIL N 2010",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "RTV-1 Silicone Rubber",
    completeness: 35,
    physical_form: "Self-leveling",
    cure_system: "Moisture",
    main_application: "Horizontal sealing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-rubber/moisture-curing-silicone-rubber-rtv-1/elastosil-n-2010/p/000005121",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Self-leveling RTV-1 silicone rubber for horizontal sealing applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-n-2076",
    name: "ELASTOSIL N 2076",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "RTV-1 Silicone Rubber",
    completeness: 35,
    physical_form: "Flowable",
    cure_system: "Moisture",
    main_application: "Coating/encapsulation",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-rubber/moisture-curing-silicone-rubber-rtv-1/elastosil-n-2076/p/000005118",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Flowable RTV-1 silicone rubber for coating and encapsulation applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-n-2189",
    name: "ELASTOSIL N 2189",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "RTV-1 Silicone Rubber",
    completeness: 35,
    physical_form: "Non-slumping",
    cure_system: "Alkoxy",
    main_application: "Construction sealing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-rubber/moisture-curing-silicone-rubber-rtv-1/elastosil-n-2189/p/000005120",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Non-slumping alkoxy-curing RTV-1 silicone rubber for construction sealing.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-n-2199",
    name: "ELASTOSIL N 2199",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "RTV-1 Silicone Rubber",
    completeness: 35,
    physical_form: "Non-slumping paste",
    cure_system: "Moisture",
    main_application: "General sealing",
    product_url:
      "https://www.wacker.com/h/en-us/silicone-rubber/moisture-curing-silicone-rubber-rtv-1/elastosil-n-2199/p/000005119",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Non-slumping RTV-1 silicone rubber paste for general sealing applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-e4",
    name: "ELASTOSIL E4",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Two-Component Silicone Elastomers",
    completeness: 30,
    main_application: "Two-component elastomer",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Two-component silicone elastomer for industrial applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-lr-3040-40",
    name: "ELASTOSIL LR 3040:40 A:B",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Liquid Silicone Rubber (LSR)",
    completeness: 93,
    physical_form: "Paste (both A & B components, flowable paste)",
    density: "1.12 g/cm\u00B3 (cured @ 23\u00B0C)",
    flash_point: "> 200\u00B0C",
    cure_system: "Addition",
    main_application: "Food-contact applications, FDA \u00A7 177.2600 compliant",
    extraction_status: "complete",
    grade:
      "Food Contact Grade - FDA 21 CFR 177.2600, BfR XV Recommendation",
    chemical_synonyms: "Two-component liquid silicone rubber",
    wiaw_status: "GREEN",
    producer: "Wacker Chemie AG",
    description:
      "Two-component liquid silicone rubber for food-contact applications with FDA compliance.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-lr-3065-30",
    name: "ELASTOSIL LR 3065:30 A:B",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Liquid Silicone Rubber (LSR)",
    completeness: 86,
    physical_form: "Paste (both A & B components, flowable)",
    density: "1.12 g/cm\u00B3 (cured @ 23\u00B0C)",
    flash_point: "320\u00B0C",
    cure_system: "Addition",
    main_application: "Pharmaceutical applications, medical devices",
    chemical_synonyms: "Pharmaceutical grade LSR",
    extraction_status: "partial",
    grade: "Technical Grade (not pharmaceutical/food compliant)",
    producer: "Wacker Chemie AG",
    description:
      "Two-component liquid silicone rubber for pharmaceutical and medical device applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-lr-3065-50",
    name: "ELASTOSIL LR 3065:50 A:B",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Liquid Silicone Rubber (LSR)",
    completeness: 86,
    physical_form: "Paste (flowable, 2 components A & B, Shore A 50)",
    density: "1.12 g/cm\u00B3 (cured @ 23\u00B0C)",
    flash_point: "340\u00B0C",
    cure_system: "Addition",
    main_application: "Pharmaceutical applications, high-temperature stability",
    chemical_synonyms: "Pharmaceutical grade LSR",
    extraction_status: "partial",
    grade: "Pharma Quality / Technical (not food contact)",
    producer: "Wacker Chemie AG",
    description:
      "Two-component liquid silicone rubber with high-temperature stability for pharmaceutical use.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-lr-3066-40",
    name: "ELASTOSIL LR 3066:40 A:B",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Liquid Silicone Rubber (LSR)",
    completeness: 86,
    physical_form: "Paste (A & B components, flowable, easily pigmentable)",
    density: "1.12 g/cm\u00B3 (cured @ 23\u00B0C, post-cured)",
    flash_point: "> 300\u00B0C",
    cure_system: "Addition",
    main_application: "Food-contact applications, high thermal stability",
    chemical_synonyms: "Food-grade LSR, high temperature",
    extraction_status: "partial",
    grade:
      "Food Contact Grade - FDA 21 CFR 177.2600, BfR XV Recommendation",
    producer: "Wacker Chemie AG",
    description:
      "Two-component food-grade liquid silicone rubber with high thermal stability.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "elastosil-lr-3675-30",
    name: "ELASTOSIL LR 3675:30 A:B",
    brand: "ELASTOSIL",
    product_line: "ELASTOSIL\u00AE",
    category: "Liquid Silicone Rubber (LSR)",
    completeness: 86,
    physical_form: "Paste (flowable, self-adhesive, both A & B)",
    density: "1.12 g/cm\u00B3 (cured @ 23\u00B0C)",
    flash_point: "Exempt",
    cure_system: "Addition",
    main_application: "Industrial applications, general purpose LSR",
    cas_numbers: "2530-83-8",
    chemical_components: "Glycidoxypropyltrimethoxysilane",
    chemical_synonyms: "Technical grade LSR",
    extraction_status: "partial",
    grade:
      "Technical Grade (self-adhesive, not pharmaceutical/food)",
    producer: "Wacker Chemie AG",
    description:
      "Self-adhesive two-component liquid silicone rubber for general industrial applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },

  // ============================================================
  // FERMOPURE products (12)
  // ============================================================
  {
    id: "fermopure-nat-l-cystine-food",
    name: "FERMOPURE Natural L-Cystine FOOD",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 94,
    physical_form: "White crystalline powder (practically insoluble in water)",
    cas_numbers: "56-89-3",
    chemical_synonyms: "L-Cystine, E920",
    main_application: "Food supplements, bakery",
    grade: "Food Grade - EP / E920",
    purity: "min. 98.5-101.5%",
    extraction_status: "complete",
    wiaw_status: "GREEN",
    producer: "Wacker Chemie AG",
    description:
      "L-Cystine amino acid dimer produced via fermentation from non-animal raw materials for food applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-nat-l-cystine-infant",
    name: "FERMOPURE Natural L-Cystine INFANT FOOD",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 45,
    physical_form: "Powder (white)",
    chemical_synonyms: "L-Cystine (Infant Formula Grade)",
    main_application: "Infant formula, baby food",
    grade: "Infant Food Grade",
    purity: "\u226598%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cystine-products/fermopure-natural-l-cystine-infant-food/p/000014051",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "L-Cystine amino acid for infant formula and baby food applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-l-cystine-pharma",
    name: "FERMOPURE L-Cystine PHARMA",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 50,
    physical_form: "Powder",
    cas_numbers: "56-89-3",
    chemical_synonyms: "C\u2086H\u2081\u2082N\u2082O\u2084S\u2082",
    main_application: "Pharmaceutical excipient",
    grade: "Pharma Grade",
    purity: "98.5-101.0%",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Pharmaceutical grade L-Cystine produced via fermentation for pharma excipient and API synthesis.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-l-cystine-pharma-ls",
    name: "FERMOPURE L-CYSTINE PHARMA Low Sulfate",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 50,
    physical_form: "Powder (white, crystalline)",
    chemical_synonyms: "L-Cystine (Low Sulfate)",
    main_application: "Sensitive pharma applications",
    grade: "Pharma Grade (Low Sulfate)",
    purity: "98.5 - 101.0%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cystine-products/fermopure-l-cystine-pharma-low-sulfate/p/000012001",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Low sulfate pharmaceutical grade L-Cystine for sensitive pharma applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-l-cysteine-pharma",
    name: "FERMOPURE L-Cysteine PHARMA",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 50,
    physical_form: "Powder",
    cas_numbers: "7048-04-6",
    main_application: "Pharma excipient and API synthesis",
    grade: "Pharma Grade",
    purity: "98.5-101.0%",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "L-Cysteine Hydrochloride Monohydrate for pharmaceutical excipient and API synthesis applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-l-cysteine-pharma-fb",
    name: "FERMOPURE L-Cysteine PHARMA FB",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 50,
    physical_form: "Granules (fluid bed processed)",
    chemical_synonyms: "L-Cysteine HCl\u00B7H\u2082O (FB)",
    main_application: "Improved flowability pharma applications",
    grade: "Pharma Grade (Fluid Bed)",
    purity: "98.5 - 101.0%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cysteine-products/fermopure-l-cysteine-pharma-fb/p/000023053",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Fluid bed processed L-Cysteine for pharma applications with improved flowability.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-l-cysteine-pharma-endotox",
    name: "FERMOPURE L-Cysteine PHARMA ENDOTOX",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 50,
    physical_form: "Powder (white, crystalline)",
    chemical_synonyms: "L-Cysteine HCl\u00B7H\u2082O (Low Endotoxin)",
    main_application: "Sterile pharma applications",
    grade: "Pharma Grade (Low Endotoxin)",
    purity: "98.5 - 101.0%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cysteine-products/fermopure-l-cysteine-pharma-endotox/p/000014070",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Low endotoxin L-Cysteine for sterile pharmaceutical applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-vegan-l-cysteine-food",
    name: "FERMOPURE Vegan L-Cysteine FOOD",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 94,
    physical_form: "White crystalline powder, 20 Mesh",
    chemical_synonyms: "L-Cysteine HCl\u00B7H\u2082O, E920, 20 Mesh",
    main_application: "Vegan food applications",
    grade: "Food Grade - EP / E920",
    purity: "min 98.5%",
    extraction_status: "complete",
    wiaw_status: "GREEN",
    producer: "Wacker Chemie AG",
    description:
      "Vegan L-Cysteine Hydrochloride Monohydrate for food applications produced via fermentation.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-vegan-l-cysteine-food-a",
    name: "FERMOPURE Vegan L-Cysteine FOOD A",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 45,
    physical_form: "Powder",
    chemical_synonyms: "L-Cysteine base (Vegan)",
    main_application: "Vegan food applications",
    grade: "Food Grade (Vegan)",
    purity: "\u226598%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cysteine-products/fermopure-vegan-l-cysteine-food-a/p/000012016",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description: "Vegan L-Cysteine base for food applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-vegan-l-cysteine-food-fb",
    name: "FERMOPURE Vegan L-Cysteine FOOD FB",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 45,
    physical_form: "Granules (fluid bed processed)",
    chemical_synonyms: "L-Cysteine base (Vegan, FB)",
    main_application: "Vegan food with improved flowability",
    grade: "Food Grade (Vegan, Fluid Bed)",
    purity: "\u226598%",
    product_url:
      "https://www.wacker.com/h/en-us/amino-acids/cysteine-products/fermopure-vegan-l-cysteine-food-fb/p/000012017",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Fluid bed processed vegan L-Cysteine for food applications with improved flowability.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-vegan-l-cysteine-infant",
    name: "FERMOPURE Vegan L-Cysteine INFANT FOOD",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 45,
    physical_form: "Powder",
    main_application: "Vegan infant food",
    grade: "Infant Food Grade (Vegan)",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Vegan L-Cysteine for infant formula and baby food applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "fermopure-vegan-l-cysteine-food-lp",
    name: "FERMOPURE VEGAN L-CYSTEIN FOOD 20 Low Perchlorate",
    brand: "FERMOPURE",
    product_line: "FERMOPURE\u00AE",
    category: "Amino Acids",
    completeness: 45,
    physical_form: "Powder",
    main_application: "Low perchlorate vegan food",
    grade: "Food Grade (Vegan, Low Perchlorate)",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Low perchlorate vegan L-Cysteine for food applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },

  // ============================================================
  // GENIOSIL products (15)
  // ============================================================
  {
    id: "geniosil-gf-56",
    name: "GENIOSIL GF 56",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 94,
    physical_form: "Liquid",
    cas_numbers: "78-08-0",
    density: "0.91 g/cm\u00B3",
    flash_point: "37\u00B0C",
    purity: ">98%",
    main_application: "Coupling agent, adhesion promoter",
    product_url:
      "https://www.wacker.com/h/en-us/silanes-siloxanes-silicates/organofunctional-silanes/geniosil-gf-56/p/000098819",
    extraction_status: "complete",
    wiaw_status: "GREEN",
    shelf_life: "12 months",
    grade: "Technical Grade",
    chemical_synonyms: "Vinyltriethoxysilane",
    producer: "Wacker Chemie AG",
    description:
      "Vinyltriethoxysilane used as coupling agent and adhesion promoter for mineral-filled plastics.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-gptm",
    name: "GENIOSIL GPTM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    cas_numbers: "2530-83-8",
    main_application: "Coupling agent for mineral-filled plastics",
    product_url:
      "https://www.wacker.com/h/en-us/silanes-siloxanes-silicates/organofunctional-silanes/geniosil-gptm/p/000098829",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "3-Glycidoxypropyltrimethoxysilane. Epoxyfunctional alkoxysilane used as coupling agent and adhesion promoter.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-gpte",
    name: "GENIOSIL GPTE",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    main_application: "Epoxy-functional silane",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Epoxyfunctional alkoxysilane (triethoxysilane variant) for adhesion promotion and surface modification.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-aptm",
    name: "GENIOSIL APTM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    cas_numbers: "13822-56-5",
    main_application: "Adhesion promoter, surface modifier",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "3-Aminopropyltrimethoxysilane. Aminofunctional alkoxysilane serving as adhesion promoter and surface modifier.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-apte",
    name: "GENIOSIL APTE",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    main_application: "Amino-functional silane",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Aminopropyltriethoxysilane for adhesion promotion and surface modification applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-mptm",
    name: "GENIOSIL MPTM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    main_application: "Mercapto-functional silane",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Mercaptopropyltrimethoxysilane for rubber reinforcement and adhesion promotion.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-ptm",
    name: "GENIOSIL PTM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    main_application: "Phenyl-functional silane",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Phenyltrimethoxysilane for surface treatment and resin modification applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-vtm",
    name: "GENIOSIL VTM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    main_application: "Vinyl-functional crosslinker",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Vinyltrimethoxysilane for crosslinking and surface modification applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-vte",
    name: "GENIOSIL VTE",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    chemical_synonyms: "Vinyltriethoxysilane",
    main_application: "Vinyl-functional crosslinker",
    product_url:
      "https://www.wacker.com/h/en-us/silanes-siloxanes-silicates/organofunctional-silanes/geniosil-vte/p/000099020",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Vinyltriethoxysilane for crosslinking and surface modification applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-note",
    name: "GENIOSIL NOTE",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid",
    chemical_synonyms: "n-Octyltriethoxysilane",
    main_application: "Hydrophobic surface treatment",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "n-Octyltriethoxysilane for hydrophobic surface treatment of mineral substrates.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-dapdm",
    name: "GENIOSIL DAPDM",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 40,
    physical_form: "Liquid (clear, colorless)",
    chemical_synonyms:
      "N-(2-Aminoethyl)-3-aminopropylmethyldimethoxysilane, C\u2088H\u2082\u2082N\u2082O\u2082Si",
    main_application: "Adhesion promoter, surface modifier",
    product_url:
      "https://www.wacker.com/h/en-us/silanes-siloxanes-silicates/organofunctional-silanes/geniosil-dapdm/p/000098827",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Diaminofunctional alkoxysilane for adhesion promotion and surface modification.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-gf-9",
    name: "GENIOSIL GF 9",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 71,
    physical_form: "Liquid",
    cas_numbers: "1760-24-3, 68845-16-9, 74956-86-8, 618914-51-5",
    chemical_synonyms: "Glycidoxypropyl silane, Epoxyfunctional",
    main_application: "Amino-functional adhesion promoter",
    grade: "Technical Grade - Aminosilane Adhesion Promoter",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Multi-functional aminosilane adhesion promoter for construction and composite applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-stabilizer-t",
    name: "GENIOSIL STABILIZER T",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "STP Additives",
    completeness: 82,
    physical_form: "Liquid",
    density: "1.015 g/cm\u00B3",
    flash_point: "28\u00B0C",
    un_number: "1993",
    main_application: "Stabilizer for STP polymers",
    extraction_status: "partial",
    wiaw_status: "GREEN",
    producer: "Wacker Chemie AG",
    description:
      "Stabilizer for silane-terminated polymer (STP) based adhesives and sealants.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-xl-10",
    name: "GENIOSIL XL 10",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 100,
    physical_form: "Colourless, clear liquid with weak odour",
    cas_numbers: "2768-02-7, 049-00-0",
    density: "0.97 g/cm\u00B3 @ 25\u00B0C",
    flash_point: "25\u00B0C",
    chemical_synonyms: "Extended-chain alkoxysilane",
    main_application: "Extended functionality, surface treatment",
    grade: "Technical Grade - Extended-Chain Vinyl Silane",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Extended-chain vinyl alkoxysilane for surface treatment and crosslinking applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "geniosil-xt-120",
    name: "GENIOSIL XT 120",
    brand: "GENIOSIL",
    product_line: "GENIOSIL\u00AE",
    category: "Organofunctional Silanes",
    completeness: 80,
    physical_form: "Clear to slightly yellow liquid",
    cas_numbers: "2996-92-1, 23432-65-7",
    density: "1.14 g/cm\u00B3 @ 20\u00B0C",
    flash_point: "97\u00B0C",
    chemical_synonyms: "Extended functionality silane",
    main_application: "Extended functionality, adhesion promotion",
    grade: "Technical",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Extended functionality silane for adhesion promotion and polymer modification.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },

  // ============================================================
  // POWERSIL products (4)
  // ============================================================
  {
    id: "powersil-79032",
    name: "POWERSIL 79032",
    brand: "POWERSIL",
    product_line: "POWERSIL\u00AE",
    category: "Conductive Silicone Rubber",
    completeness: 100,
    physical_form: "Dispersion",
    cas_numbers: "1330-20-7, 100-41-4, 108-88-3",
    chemical_components: "INHA, Ethylbenzene, Toluene",
    chemical_synonyms: "Silikon-Gummi-Dispersion in Xylol",
    density: "1.22 g/cm\u00B3 @ 23\u00B0C (cured)",
    main_application: "Specialized power equipment, conductive silicone",
    grade: "Technical Grade - Conductive Silicone Rubber Dispersion",
    extraction_status: "complete",
    wiaw_status: "RED",
    sales_advisory:
      "\uD83D\uDED1 STOP - Geographic compliance violation. 8 blocked countries: Japan, Australia, China, Canada, USA, Philippines, Taiwan, South Korea.",
    blocked_countries: [
      "Japan",
      "Australia",
      "China",
      "Canada",
      "USA",
      "Philippines",
      "Taiwan",
      "South Korea",
    ],
    producer: "Wacker Chemie AG",
    description:
      "Conductive silicone rubber dispersion in xylol for specialized power equipment and electrical applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "powersil-310-mh",
    name: "POWERSIL 310 MH",
    brand: "POWERSIL",
    product_line: "POWERSIL\u00AE",
    category: "HCR/HTV Silicone Rubber",
    completeness: 100,
    physical_form: "Solid (high consistency rubber/paste, one-component)",
    density: "1.55 g/cm\u00B3 (cured, high-density)",
    chemical_synonyms: "Polydimethylsiloxane (Peroxid-Vernetzung)",
    main_application:
      "High-voltage transmission, transformer components, power line insulators",
    grade: "Technical Grade - HCR/HTV (Peroxide-curing, T&D)",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "High consistency silicone rubber for high-voltage transmission and power line insulator applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "powersil-190-mh",
    name: "POWERSIL 190 MH",
    brand: "POWERSIL",
    product_line: "POWERSIL\u00AE",
    category: "HCR/HTV Silicone Rubber",
    completeness: 100,
    physical_form: "Solid (high consistency rubber)",
    cas_numbers: "68909-20-6, 052-00-7",
    chemical_components:
      "silanamine, trimethylsilyl, hydrolysis products with silica",
    chemical_synonyms: "Polydimethylsiloxane (Peroxid-Vernetzung)",
    density: "1.58 g/cm\u00B3 (cured, filler-loaded)",
    main_application: "Power equipment, insulation",
    grade: "Technical Grade - HCR/HTV (Peroxide-curing, T&D)",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Filler-loaded high consistency silicone rubber for power equipment insulation applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "powersil-paste-ap",
    name: "POWERSIL PASTE AP",
    brand: "POWERSIL",
    product_line: "POWERSIL\u00AE",
    category: "Silicone Pastes",
    completeness: 100,
    physical_form: "Paste (opaque to whitish, medium consistency)",
    cas_numbers: "33204-76-1",
    chemical_components:
      "2,2,4,6,6,8-Hexamethyl-4,8-diphenylcyclotetrasiloxane",
    chemical_synonyms: "Silikon-Paste mit Phenyl-Silikon-\u00D6l",
    density: "1.1 g/cm\u00B3 @ 23\u00B0C",
    main_application:
      "Power equipment assembly, thermal interface applications",
    grade:
      "Technical Grade - Silicone Paste (Non-curing, Sealant & Lubricant)",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Silicone paste with phenyl silicone oil for power equipment assembly and thermal interface applications.",
    tds_available: true,
    sds_available: true,
    rpi_available: true,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },

  // ============================================================
  // VINNAPAS products (27)
  // ============================================================
  {
    id: "vinnapas-301",
    name: "VINNAPAS 301",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "General construction, bonding applications, coatings",
    wacker_sku: "000008920",
    product_url:
      "https://www.wacker.com/h/en-us/polymer-dispersions/vinnapas-301/p/000008920",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Vinyl acetate-ethylene polymer dispersion for general construction and coating applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-303",
    name: "VINNAPAS 303",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "Construction adhesives",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE polymer dispersion for construction adhesive applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-305",
    name: "VINNAPAS 305",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "Construction coatings",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE polymer dispersion for construction coating applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-315",
    name: "VINNAPAS 315",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "Flexible bonding",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE polymer dispersion for flexible bonding applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-323",
    name: "VINNAPAS 323",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "Construction materials",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE polymer dispersion for construction material applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-400",
    name: "VINNAPAS 400",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion (aqueous)",
    chemical_synonyms: "VAE dispersion, Tg: 0\u00B0C",
    main_application: "High-performance adhesive",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-400/p/000008929",
    extraction_status: "in_progress",
    temperature_range: "Tg: 0\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "VAE dispersion for high-performance adhesive applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-401",
    name: "VINNAPAS 401",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion (aqueous)",
    chemical_synonyms: "VAE dispersion, Tg: -15\u00B0C",
    main_application: "General purpose adhesive",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-401/p/000008931",
    extraction_status: "in_progress",
    temperature_range: "Tg: -15\u00B0C",
    producer: "Wacker Chemie AG",
    description:
      "VAE dispersion for general purpose adhesive applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-418",
    name: "VINNAPAS 418",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion (aqueous)",
    main_application: "Adhesive applications",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE dispersion for versatile adhesive applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-530-nd",
    name: "VINNAPAS 530 ND",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion",
    main_application: "Non-dusting polymer dispersion",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Non-dusting VAE polymer dispersion for construction applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-550-ed",
    name: "VINNAPAS 550 ED",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion",
    main_application: "Enhanced dispersion",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Enhanced VAE polymer dispersion for construction applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-920",
    name: "VINNAPAS 920",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 30,
    physical_form: "Polymer Dispersion",
    main_application: "Construction materials",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "VAE polymer dispersion for construction material applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-2012-e",
    name: "VINNAPAS 2012 E",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 93,
    physical_form: "White to light beige free-flowing powder",
    density: "Bulk density: 350-550 kg/m\u00B3 (for powder)",
    chemical_synonyms: "VAE Copolymer (Vinyl Acetate-Ethylene)",
    main_application: "Construction materials, adhesives",
    grade: "Technical Grade - Dispersible Polymer Powder",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder based on VAE copolymer for construction materials and adhesives.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-4712-n",
    name: "VINNAPAS 4712 N",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder (dispersible)",
    main_application: "Good wood adhesion, water resistant",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for tile adhesives with optimum adhesion to wood and excellent water resistance.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-4713-n",
    name: "VINNAPAS 4713 N",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder (dispersible)",
    chemical_synonyms: "VAE dispersible polymer powder",
    main_application: "Good wood adhesion, water resistant",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-4713-n/p/000010665",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for tile adhesives with enhanced wood adhesion and water resistance.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-5010-n-kor",
    name: "VINNAPAS 5010 N (KOR)",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 93,
    physical_form: "White to light beige free-flowing powder (redispersible)",
    density: "Bulk density: 350-500 kg/m\u00B3 (for powder)",
    chemical_synonyms: "VAE Copolymer (Vinyl Acetate-Ethylene)",
    main_application: "Tile adhesives, construction mortars",
    grade: "Technical Grade - Redispersible Polymer Powder",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Redispersible polymer powder for tile adhesives and construction mortars.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-5044-n-uls",
    name: "VINNAPAS 5044 N (ULS)",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 93,
    physical_form: "White to light beige free-flowing powder",
    density: "Bulk density: 350-500 kg/m\u00B3 (for powder)",
    chemical_synonyms: "VAE Copolymer (Vinyl Acetate-Ethylene)",
    main_application: "Ultra-low shrinkage mortars",
    grade: "Technical Grade - Ultra Low Sulfate Redispersible Polymer",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Ultra-low sulfate redispersible polymer powder for ultra-low shrinkage mortars.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-5047-t",
    name: "VINNAPAS 5047 T",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 93,
    physical_form: "White to light beige free-flowing powder",
    purity: "min 98%",
    main_application: "Construction mortars",
    extraction_status: "complete",
    wiaw_status: "GREEN",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for construction mortar applications with high purity.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-5129-l",
    name: "VINNAPAS 5129 L",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder",
    main_application: "Construction additives",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for construction additive applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-5343-e",
    name: "VINNAPAS 5343 E",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder (dispersible)",
    chemical_synonyms: "VAE dispersible powder, flexible",
    main_application: "Flexible, wash-out resistant paver joints",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-5343-e/p/000010692",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for paver joint sand with flexibility and wash-out resistance.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-8812-t",
    name: "VINNAPAS 8812 T",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder",
    main_application: "Construction materials",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for construction material applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-af-875",
    name: "VINNAPAS AF 875",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder",
    main_application: "Anti-foaming applications",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder with anti-foaming properties for construction applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-ca-5544",
    name: "VINNAPAS CA 5544",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 35,
    physical_form: "Powder",
    main_application: "Construction adhesive",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Dispersible polymer powder for construction adhesive formulations.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-ef-811",
    name: "VINNAPAS EF 811",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion (aqueous)",
    chemical_synonyms: "VAE dispersion, Environmental Focus",
    main_application: "Environmental focus, acrylic replacement",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-ef-811/p/000008900",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Environmental-focus VAE dispersion as acrylic replacement for coatings.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-ef-8300",
    name: "VINNAPAS EF 8300",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion (aqueous)",
    chemical_synonyms: "VAE dispersion, Architectural coating",
    main_application: "Architectural coating, high performance",
    product_url:
      "https://www.wacker.com/h/en-us/c/vinnapas-ef-8300/p/000008901",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "High-performance VAE dispersion for architectural coating applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-ef-539",
    name: "VINNAPAS EF 539",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 35,
    physical_form: "Dispersion",
    main_application: "Environmental focus dispersion",
    extraction_status: "in_progress",
    producer: "Wacker Chemie AG",
    description:
      "Environmental-focus VAE dispersion for sustainable construction applications.",
    tds_available: false,
    sds_available: false,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-eco-8251",
    name: "VINNAPAS eco 8251 (XX MB)",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Dispersible Polymer Powders",
    completeness: 86,
    physical_form: "White free-flowing powder (eco-certified)",
    density: "Bulk density: 400-500 kg/m\u00B3 (eco powder)",
    chemical_synonyms: "VAE Copolymer",
    main_application: "Eco-friendly construction materials",
    grade: "Technical Grade - Eco Variant (Sustainable)",
    extraction_status: "partial",
    producer: "Wacker Chemie AG",
    description:
      "Eco-certified dispersible polymer powder for sustainable construction materials.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
  {
    id: "vinnapas-eco-en-1024",
    name: "VINNAPAS eco EN 1024 (XX MB)",
    brand: "VINNAPAS",
    product_line: "VINNAPAS\u00AE",
    category: "Polymer Dispersions",
    completeness: 93,
    physical_form: "White liquid dispersion (eco-certified)",
    density: "approx. 1.04 g/cm\u00B3 @ 20\u00B0C (liquid density)",
    chemical_synonyms: "VAE Copolymer Dispersion",
    main_application: "Eco-friendly adhesives, coatings",
    grade: "Technical Grade - Eco EN 1024 Standard Compliant",
    extraction_status: "complete",
    producer: "Wacker Chemie AG",
    description:
      "Eco-certified VAE copolymer dispersion for sustainable adhesives and coatings.",
    tds_available: true,
    sds_available: true,
    rpi_available: false,
    coa_available: false,
    key_properties: [],
    applications: [],
    benefits: [],
  },
];
