"""add industry_events tables

Revision ID: 8eaa5db9abe4
Revises: 
Create Date: 2026-02-09 14:26:34.279177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8eaa5db9abe4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_collector_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('events_found', sa.Integer(), nullable=False),
    sa.Column('events_new', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=15, scale=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_title', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('companies', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('company_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('products', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('segments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('regions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('deal_value', sa.Text(), nullable=True),
    sa.Column('deal_duration', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('geographic_scope', sa.Text(), nullable=True),
    sa.Column('exec_quotes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_people', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategic_rationale', sa.Text(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notion_page_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash')
    )
    op.create_index('idx_industry_events_created', 'industry_events', ['created_at'], unique=False)
    op.create_index('idx_industry_events_date', 'industry_events', ['event_date'], unique=False)
    op.create_index('idx_industry_events_dedup', 'industry_events', ['dedup_hash'], unique=False)
    op.create_index('idx_industry_events_source', 'industry_events', ['source_name'], unique=False)
    op.create_index('idx_industry_events_type', 'industry_events', ['event_type'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cas_number', sa.String(length=20), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('scraper_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_raw', sa.Text(), nullable=False),
    sa.Column('price_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_unit', sa.String(length=20), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('price_type', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_prices_product', 'market_prices', ['product_id'], unique=False)
    op.create_index('idx_market_prices_source', 'market_prices', ['source'], unique=False)
    op.create_index('idx_market_prices_time', 'market_prices', ['time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_provider_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('internal_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_raw', sa.Text(), nullable=False),
    sa.Column('price_value', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('price_currency', sa.String(length=3), nullable=False),
    sa.Column('price_unit', sa.String(length=20), nullable=False),
    sa.Column('price_raw', sa.Text(), nullable=True),
    sa.Column('specs', sa.Text(), nullable=True),
    sa.Column('delivery_term', sa.String(length=10), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('packaging', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('producer', sa.Text(), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_internal_prices_created', 'internal_prices', ['created_at'], unique=False)
    op.create_index('idx_internal_prices_org', 'internal_prices', ['org_id'], unique=False)
    op.create_index('idx_internal_prices_product', 'internal_prices', ['product_id'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('condition_type', sa.String(length=20), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sources', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('channels', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_favorites')
    op.drop_table('price_alerts')
    op.drop_index('idx_internal_prices_product', table_name='internal_prices')
    op.drop_index('idx_internal_prices_org', table_name='internal_prices')
    op.drop_index('idx_internal_prices_created', table_name='internal_prices')
    op.drop_table('internal_prices')
    op.drop_table('users')
    op.drop_index('idx_market_prices_time', table_name='market_prices')
    op.drop_index('idx_market_prices_source', table_name='market_prices')
    op.drop_index('idx_market_prices_product', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_table('scraper_runs')
    op.drop_table('products')
    op.drop_table('organizations')
    op.drop_index('idx_industry_events_type', table_name='industry_events')
    op.drop_index('idx_industry_events_source', table_name='industry_events')
    op.drop_index('idx_industry_events_dedup', table_name='industry_events')
    op.drop_index('idx_industry_events_date', table_name='industry_events')
    op.drop_index('idx_industry_events_created', table_name='industry_events')
    op.drop_table('industry_events')
    op.drop_table('exchange_rates')
    op.drop_table('event_collector_runs')
    # ### end Alembic commands ###
